<hr/>
<div data-bind="scope: 'section'">
    <div data-bind="html: custom_message().custom_message"></div>
</div>
<hr/>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Kom_HelloWorld/js/section"
                    }
                }
            }
        }
    }
</script>